// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package scouter

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "scouter", asset.ModuleFieldsPri, AssetScouter); err != nil {
		panic(err)
	}
}

// AssetScouter returns asset data.
// This is the base64 encoded gzipped contents of module/scouter.
func AssetScouter() string {
	return "eJykl11yrCoQx99nFVTecxfgw93BWQPFYGtIEAg0k+PuT6GOMWZAp5mHpEr9/5r+guaVfcDYsCBtRPAXxlChhoa9LE9eLoy1EKRXDpU1Dfv/whi7f8/+2DZquDDWKdBtaKaXr8yIAbbQ9MPRQcN6b6Nbnjzg/gRtYdr267NHsCxw/t0XLG006b9WBsJ/m0/2djdugL+tXpTMP4KsHNYw1f58MXNYk1LwZX37wLa9voNEuu0VlP7urS+o39a3wjcR3kjC9A3Nog1IEv6O7ylZJwal9Xhae9e9i5sAOJWbQmF+l+bMu1foE7kVEtUNeKpTJXMxVwah32E3CKc4eG899wJziE5bsc/MFoAuUJUqW53amv5Aya9jlfOghQvQcqGHfOmdQxQcOQDUBL+XfKoakuVeEsP/BsJxtCg0YcmTOAbItWxJ68AP3IGXkHX5UE407SEZTep9OM8FeynTinSFT13XqQlA69RJSS3wu7i2Wc8vPXueVO3Sv2jlvVm6yCMqSou0KnxwD6Ll1xEh53WhQSfAl1cIVMIAA3X1Sdp5oCU5iUs7y7G60N9lsQHkylxtNHS9jVgH8H+LGTsGYA0gfAnHneiBK1MJsJG4yyUCsfImLb16ZtPU8glj4NJFwrJROh5QIJealrYVAMQhZgV0xLyvAFQDCZDO1SfCt9r1QqrdJla1yS8H1AQGpkxnnxnHtbaSDzBYn7tUHAy1UmhdMSKsCNpcl6TZ8aZ8lcqn7tT4TNOaeezm4KzMXVUL7s7DlBQx0K6rynHRttlx0BXmobopkJbdgMLj0wH7nn8/nbeyvtPQDlLg2mgePiMEZAkOIRAuwdNxx9N8rm7ZSirEZdaH/JXiuITI2Vy8VqYnJnUJ36kl/AsAAP//oMLd8w=="
}
