// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package scouter

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "scouter", asset.ModuleFieldsPri, AssetScouter); err != nil {
		panic(err)
	}
}

// AssetScouter returns asset data.
// This is the base64 encoded gzipped contents of module/scouter.
func AssetScouter() string {
	return "eJykmEty4yAQhvc+BZV95gBazA3mDBRGbZkEAYHGiW8/hV5RFIPkxoukStL/NfQDdeuVvcO9YUHaiOBPjKFCDQ17ma68nBhrIUivHCprGvb3xBibn2f/bBs1nBi7KNBtaIabr8yIHtbQ9MO7g4Z13kY3XXnA/Qlaw7TtlmuPYFng+JsXLG006b9WBsKf1SNbu6ttgL8tuyiZfwRZOKxhqv15Y+SwJoXg0/r2gW17fgOJdNsLKP3dWp9Qv62vhVcRriRheoZm0QYkCX/795DsInql74els+xN3ATAodAU8vI7M0fenKBPhFZIVDfgKU2VzLlcGYRug10hnOLgvfXcC8whLtqKbWDWAHSBqlTZ5NTWdDtKfr5XbR60cAFaLnSfz7xjiMJGdgA1zu8kH7KGZLmTRPdfQTiOFoUmLHkQxwC5ii1pHfieO/ASslvelRNNe0hGk3rrzmPOntK0IlzhQ9dVagLQKnVQUhN8FtcW6/GlZ18nVaf0L1r5bJYu8oiKUiKtCu/cg2j5+Y6Q23WhQAfAp1cIVEIPPXX1SXrxQAtyEpdOln11ob7LYgPIlTnbaOh6G7EO4L+KEdsHYA0gfArHneiAK1MJsJF4yiUCMfMGLT17RtPU9An3wKWLhGWjdDygQC41LWwLAIhNzAK4EOO+AFD1JEB6rz7hvsWuF1JtDrGqQ356QQ1gYMpc7DPtuNZW8h5663NDxU5TK4XWFS3CgqD1dUmabW/Kk1Q+dIfaZ5rWjG03B2dlblItbHdopip6dilioM25ynHRtlnbrtBJ1fWPtLwIKDxWuRq/OHFE78jKueMmf//A69CDPaX/Hhc+nLey/mBC20uBy7nk4SNCQJbgEALhm8HQHfA0zqhbtvAKoRz1IT+B7VVcRQpPu1amI2by5L5DS/gfAAD//0aBJWY="
}
