// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package scouter

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "scouter", asset.ModuleFieldsPri, AssetScouter); err != nil {
		panic(err)
	}
}

// AssetScouter returns asset data.
// This is the base64 encoded gzipped contents of module/scouter.
func AssetScouter() string {
	return "eJy0l11ypCAQx9/nFFTeswfwYW+wZ6AY7DEkCASayXr7LdQxxhnQaWrnIalS/7+mv6B5ZR8wNCxIGxH8iTFUqKFhL/OTlxNjLQTplUNlTcN+nxhjt+/ZH9tGDSfGLgp0G5rx5Sszooc1NP1wcNCwztvo5icPuD9Ba5i23fLsESwLnH63BUsbTfqvlYHwa/XJ1u7KDfDXxYuS+UeQhcMaptqfLyYOa1IKvqxvH9i253eQSLe9gNLfrfUZdW99LXwT4Y0kTN/QLNqAJOF9fA/JLqJXWg+HtTfdu7gKgEO5KRTmd2lOvFuFPpFbIVFdgac6VTIXc2UQug12hXCKg/fWcy8wh7hoK7aZWQPQBapSZatTW9PtKPl5qHIetHABWi50ny+9Y4iCIzuAmuB3ko9VQ7LcSWL430A4jhaFJix5FMcAuZYtaR34njvwErIu78qJpj0ko0m9DeexYM9lWpGu8KnrOjUBaJ06KqkFfhPXNuvxpWfPk6pd+o5W3pulizyiorRIq8IH9yBafh4Qcl4XGnQEfHmFQCX00FNXn6QXD7QkJ3FpZ9lXF/q7LDaAXJmzjYautxHrAP5vMWP7AKwBhC/huBMdcGUqATYSd7lEIFbeqKVXz2SaWj5hCFy6SFg2SscDCuRS09K2AIA4xCyACzHvCwBVTwKkc/WJ8C12vZBqs4lVbfLzATWCgSlzsc+M41pbyXvorc9dKnaGWim0rhgRFgRtrkvS7HhTvkrlU3dofKZpzTR2c3BW5q6qBXenYYoebeW4aNvsOOgK81DdFEjLbkDh8emAfc+/n85bWd9paHspcGk0D58RArIEhxAIl+DxuONpPlfXbCUV4jLpQ/5K8R9LaPZamY6Y1Dl8h5bwLwAA//+mOd30"
}
